DROP TABLE IF EXISTS LOCATION;
CREATE TABLE LOCATION
(
    ID                  	            BIGSERIAL   NOT NULL,
    DISPLAY_ADVERTISING_VEDIO_OR_IMAGE  VARCHAR     NOT NULL,
    START_DATE                          TIMESTAMP   NOT NULL,
    END_DATE                            TIMESTAMP   NOT NULL,
    ADVERTISING_ID                       BIGINT   NOT NULL,
    CONSTRAINT LOCATION_ID_PK PRIMARY KEY (ID),
    CONSTRAINT LOCATION_ADVERTISING_ID_FK FOREIGN KEY (ADVERTISING_ID) REFERENCES ADVERTISING (ID)
);