DROP TABLE IF EXISTS INVOICE;
CREATE TABLE INVOICE
(
    ID              BIGSERIAL NOT NULL,
    LINK_HTTP       VARCHAR,
    PRICE           NUMERIC,
    GENERER_FACTURE BOOLEAN,
    USER_ID			BIGINT NOT NULL,
    CONSTRAINT INVOICE_ID_PK PRIMARY KEY (ID),
    CONSTRAINT INVOICE_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USER_DETAILS (ID)
);