INSERT INTO ACTIVITY(ID,NAME)
VALUES
    (nextval('ACTIVITY_ID_SEQ'),'Alimentation'),
    (nextval('ACTIVITY_ID_SEQ'),'Animaux'),
    (nextval('ACTIVITY_ID_SEQ'),'Animé'),
    (nextval('ACTIVITY_ID_SEQ'),'Art'),
    (nextval('ACTIVITY_ID_SEQ'),'Architecture'),
    (nextval('ACTIVITY_ID_SEQ'),'Beauté'),
    (nextval('ACTIVITY_ID_SEQ'),'Bricolage'),
    (nextval('ACTIVITY_ID_SEQ'),'Business'),
    (nextval('ACTIVITY_ID_SEQ'),'Citation'),
    (nextval('ACTIVITY_ID_SEQ'),'Coiffure'),
    (nextval('ACTIVITY_ID_SEQ'),'Conseil pour parent'),
    (nextval('ACTIVITY_ID_SEQ'),'Cuisine'),
    (nextval('ACTIVITY_ID_SEQ'),'Décoration'),
    (nextval('ACTIVITY_ID_SEQ'),'Divertissement'),
    (nextval('ACTIVITY_ID_SEQ'),'Éducation'),
    (nextval('ACTIVITY_ID_SEQ'),'Électronique'),
    (nextval('ACTIVITY_ID_SEQ'),'Finance'),
    (nextval('ACTIVITY_ID_SEQ'),'Jardinage'),
    (nextval('ACTIVITY_ID_SEQ'),'Jeux vidéo'),
    (nextval('ACTIVITY_ID_SEQ'),'Life Style'),
    (nextval('ACTIVITY_ID_SEQ'),'Manga'),
    (nextval('ACTIVITY_ID_SEQ'),'Mariage'),
    (nextval('ACTIVITY_ID_SEQ'),'Mode enfant'),
    (nextval('ACTIVITY_ID_SEQ'),'Mode Femme'),
    (nextval('ACTIVITY_ID_SEQ'),'Mode Homme'),
    (nextval('ACTIVITY_ID_SEQ'),'Motivation'),
    (nextval('ACTIVITY_ID_SEQ'),'Moto'),
    (nextval('ACTIVITY_ID_SEQ'),'NFT / Crypto'),
    (nextval('ACTIVITY_ID_SEQ'),'Photographie'),
    (nextval('ACTIVITY_ID_SEQ'),'Santé'),
    (nextval('ACTIVITY_ID_SEQ'),'Sport'),
    (nextval('ACTIVITY_ID_SEQ'),'Street Art'),
    (nextval('ACTIVITY_ID_SEQ'),'Tatouage'),
    (nextval('ACTIVITY_ID_SEQ'),'Technologie'),
    (nextval('ACTIVITY_ID_SEQ'),'Voiture'),
    (nextval('ACTIVITY_ID_SEQ'),'Voyage');