DROP TABLE IF EXISTS COMPANY;
CREATE TABLE COMPANY
(
    ID                          BIGSERIAL NOT NULL,
    LOGO_LINK               	VARCHAR NOT NULL,
    BUDGET                      NUMERIC,
    DESCRIPTION_OF_COMPANY      VARCHAR,
    CONSTRAINT COMPANY_ID_PK PRIMARY KEY (ID)
);