DROP TABLE IF EXISTS MEDIA;
CREATE TABLE MEDIA
(
    ID             BIGSERIAL NOT NULL,
    LINK_HTTP      VARCHAR   NOT NULL,
    IMAGE_CATEGORY INTEGER   NOT NULL,
    FORMAT_IMAGE   VARCHAR,
    FORMAT_VIDEO   VARCHAR,
    RESOLUTION     VARCHAR,
    CUT            VARCHAR,
    DURATION       VARCHAR,
    FILE_TYPE      VARCHAR,
    FILE_NAME      VARCHAR,
    FILE_PATH      VARCHAR,
    ADVERTISING_ID BIGINT    NOT NULL,
    CONSTRAINT MEDIA_PK PRIMARY KEY (ID),
    CONSTRAINT MEDIA_ADVERTISING_ID_FK FOREIGN KEY (ADVERTISING_ID) REFERENCES ADVERTISING (ID)
);